name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
        version: "^1.0.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src
  
  style:
    name: Styling
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: "2.0.0"
        args: --check .
