name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Foreman
    uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src
  
  style:
    name: Styling
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .